"""
10 minutes to pandas (https://pandas.pydata.org/docs/user_guide/10min.html)
Intro to data structures (https://pandas.pydata.org/docs/user_guide/dsintro.html)
Essential basic functionality (https://pandas.pydata.org/docs/user_guide/basics.html)
IO tools (text, CSV, HDF5, …) (https://pandas.pydata.org/docs/user_guide/io.html)
Indexing and selecting data (https://pandas.pydata.org/docs/user_guide/indexing.html)
MultiIndex / advanced indexing (https://pandas.pydata.org/docs/user_guide/advanced.html)
Merge, join, concatenate and compare (https://pandas.pydata.org/docs/user_guide/merging.html)
Reshaping and pivot tables (https://pandas.pydata.org/docs/user_guide/reshaping.html)
Working with text data (https://pandas.pydata.org/docs/user_guide/text.html)
Working with missing data (https://pandas.pydata.org/docs/user_guide/missing_data.html)
Duplicate Labels (https://pandas.pydata.org/docs/user_guide/duplicates.html)
Categorical data (https://pandas.pydata.org/docs/user_guide/categorical.html)
Nullable integer data type (https://pandas.pydata.org/docs/user_guide/integer_na.html)
Nullable Boolean data type (https://pandas.pydata.org/docs/user_guide/boolean.html)
Visualization (https://pandas.pydata.org/docs/user_guide/visualization.html)
Computational tools (https://pandas.pydata.org/docs/user_guide/computation.html)
Group by: split-apply-combine (https://pandas.pydata.org/docs/user_guide/groupby.html)
Windowing Operations (https://pandas.pydata.org/docs/user_guide/window.html)
Time series / date functionality (https://pandas.pydata.org/docs/user_guide/timeseries.html)
Time deltas (https://pandas.pydata.org/docs/user_guide/timedeltas.html)
Styling (https://pandas.pydata.org/docs/user_guide/style.html)
Options and settings (https://pandas.pydata.org/docs/user_guide/options.html)
Enhancing performance (https://pandas.pydata.org/docs/user_guide/enhancingperf.html)
Scaling to large datasets (https://pandas.pydata.org/docs/user_guide/scale.html)
Sparse data structures (https://pandas.pydata.org/docs/user_guide/sparse.html)
Frequently Asked Questions (FAQ) (https://pandas.pydata.org/docs/user_guide/gotchas.html)
Cookbook (https://pandas.pydata.org/docs/user_guide/cookbook.html)
"""
